
CREATE TABLE categorie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL
);


CREATE TABLE produit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    description TEXT,
    prix DOUBLE PRECISION,
    quantite INTEGER,
    categorie_id BIGINT,
    CONSTRAINT fk_produit_categorie FOREIGN KEY (categorie_id) REFERENCES categorie(id)
);

CREATE INDEX idx_produit_categorie_id ON produit (categorie_id);
